### ISSUE TITLE
Android 16 beta 3 - cannot interact with screen

### ISSUE THREAD

**Issue by jpool-cf** [zacharee/NachoNotch#30]
Just updated to Android 16 beta 3 on my Pixel 8 Pro. 

When Nacho Notch is enabled, I cannot interact with anything below the status bar or scroll. 

Disabling Nacho Notch resolves the issue. 

Video of the behavior
https://photos.app.goo.gl/awnBacVumgmUZw549

**Comment by jpool-cf** [comment]
@zacharee this appears to be caused by having the Force Light Status Bar Icons option enabled. Disabling that resolves the issue.

**Comment by Arakys7** [comment]
I'm having a similar problem after updating to the Android 15 April 2025 security patch on a Pixel 7.
Disabling Nacho Notch fixed it.
I wasn't using the "Force Light Status Bar Icons" option.

**Comment by skjXvdidbiw** [comment]
Same thing happens to Android 15 with 2025 April's security patch. Cannot intercat with the screen below statusbar even with force light icon disabled.

**Comment by saki7** [comment]
Same here

**Comment by zacharee** [comment]
This should hopefully be fixed in version 43.

**Comment by jpool-cf** [comment]
> This should hopefully be fixed in version 43.

Just installed the v43 APK from here and so far so good. Thanks!

**Comment by jpool-cf** [comment]
> This should hopefully be fixed in version 43.

Ran into 1 scenario where the issue still occurs: immediately after being prompted for biometrics (banking app, Outlook, etc.)

**Comment by zacharee** [comment]
I can't figure out how to address that. There doesn't seem to be a way to detect the biometrics prompt showing without using an accessibility service. This behavior genuinely seems like a bug in Pixel UI (and not intended behavior in AOSP), especially since even telling the system that the overlay is not touchable doesn't fix dimming/blurring blocking touches in areas it doesn't even overlay.

**Comment by saki7** [comment]
@zacharee Thanks for tackling this issue.
I just installed v43 from Google Play, restarted the phone, but the issue persists.

- Google Pixel 8
- Android 15
- Android Security Update: 2025/4/5
- Google Play System Update: 2025/4/1
- Kernel version: `6.1.99-android14-11-gd7dac4b14270-ab12946699` (`#1 Tue Jan 21 13:39:43 UTC 2025`)
- Build number: `BP1A.250405.007.B1`

I'm not familiar with Android SDK, but I'm used to programming so please let me know if you need any assistance on reproducing the issue.

**Comment by saki7** [comment]
I installed v44, but still not working. The only areas I can interact with are the topmost and bottommost regions of the screen. So basically I can pull down the notifications center, can switch between active apps, but can't interact with anything on the apps.

**Comment by zacharee** [comment]
Can you try version 45? It turns out `dimAmount` can be 0 now on Android 15 and still have the effect of making the status bar icons light while also not seeming to block touches.

**Comment by saki7** [comment]
Still not working.

**Comment by saki7** [comment]
I'm not sure why "Force Light Status Bar Icons" makes any difference. Since v42, all versions prevented touch interactions on my phone. I wish I could change that config to see what happens, but unfortunately Nacho Notch is currently unconfigurable because... it prevents interactions.

**Comment by saki7** [comment]
@Dobypeti Thank god, that information was super useful.

Setting "Force Light Status Bar Icons" to OFF resolved the interaction issue; I now have the expected behavior. Setting it to ON still reproduces the issue, seems like a regression that @Dobypeti mentioned.

**Comment by sharklurk** [comment]
I'm experiencing similar behavior on android 14 after updating to June 2025 security patch. 

Forcing white icon color blocks all touch inputs besides status bar, quick settings panel, navigation bar/buttons and settings app

Touch works when force white icon color is off, but  it makes status bar black if application below it has white theme 

It behaves broadly the same on the versions from 39 to 46

I'm on motorola g24 power, so maybe whatever caused it on pixel beta is now getting ported with security updates?

**Comment by HaleyHalcyon** [comment]
Reporting that the problem pops up occasionally on my Motorola Moto g64 running Android 15 whether or not “light nav bar icons” is enabled.

I’ll try again with the GitHub release

**Comment by zacharee** [comment]
I'm giving this one final try with https://github.com/zacharee/NachoNotch/releases/tag/47

**Comment by jothki** [comment]
Nope.

I'm going to miss having this. Thanks for all the work you put into it.

**Comment by devycarol** [comment]
This is certainly an OS bug. Such seems to be the case with a lot of their "security" updates lately.

I'd say open an AOSP bug report, but given that overlays are already dark-pattern suppressed status I fear that would just cause them to remove and break them forever as they have with so many other things.

I wish Google or Lineage or *someone* would muster the courage to just kick apps out of the system bars once and for all. No rendered content, nothing. The system controls are mine, not yours. The bars should be black or a color of my choosing.

Still, a bug report might be worth a try.

**Comment by Dobypeti** [comment]
Unfortunately apps being forced to display edge-to-edge (on Android 15 and above when targeting its SDK or higher) is also a hindrance to using Nacho Notch beyond the breaking bug because of content being displayed with the whole screen in mind (possibly no extra margins and such). 🫡

**Comment by devycarol** [comment]
Sort of. It's an error to place any interactable content in the bars since they're impossible to touch. Generally, only a background display element here and there will bleed into the system bars. Like maps apps and stuff.

You're always able to scroll such content into view. If not, the app is broken and needs to be fixed.

**Comment by comettopl** [comment]
On Motorola Thinkphone it works again after update to Android 16!
